name: dialo
description: "Dialo is a powerful Dialogue Designer for Flutter. It allows you to create complex dialogues with ease. It is highly customizable and easy to use."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
